# Generated by Django 5.2.9 on 2025-12-10 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSolar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('tamanho_sistema', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tamanho do Sistema (kW)')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo Total (R$)')),
                ('data_instalacao', models.DateField(verbose_name='Data de Instalação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Cliente Ativo')),
                ('tipo_sistema', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial'), ('RURAL', 'Rural')], default='RESIDENCIAL', max_length=20, verbose_name='Tipo de Sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente Solar',
                'verbose_name_plural': 'Clientes Solares',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SistemaSolar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marca_inversor', models.CharField(max_length=100, verbose_name='Marca do Inversor')),
                ('modelo_inversor', models.CharField(max_length=100, verbose_name='Modelo do Inversor')),
                ('potencia_inversor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Potência do Inversor (kW)')),
                ('marca_painel', models.CharField(max_length=100, verbose_name='Marca do Painel')),
                ('modelo_painel', models.CharField(max_length=100, verbose_name='Modelo do Painel')),
                ('quantidade_paineis', models.IntegerField(verbose_name='Quantidade de Painéis')),
                ('potencia_painel', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Potência do Painel (W)')),
                ('orientacao', models.CharField(choices=[('NORTE', 'Norte'), ('NORDESTE', 'Nordeste'), ('LESTE', 'Leste'), ('SUDESTE', 'Sudeste'), ('SUL', 'Sul'), ('SUDOESTE', 'Sudoeste'), ('OESTE', 'Oeste'), ('NOROESTE', 'Noroeste')], max_length=20, verbose_name='Orientação')),
                ('inclinacao', models.IntegerField(verbose_name='Inclinação (graus)')),
                ('garantia_inversor', models.IntegerField(verbose_name='Garantia do Inversor (anos)')),
                ('garantia_paineis', models.IntegerField(verbose_name='Garantia dos Painéis (anos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='api.clientesolar', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Sistema Solar',
                'verbose_name_plural': 'Sistemas Solares',
            },
        ),
        migrations.CreateModel(
            name='ProducaoMensal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('producao_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Produção (kWh)')),
                ('irradiacao_media', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Irradiação Média (kWh/m²)')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='api.sistemasolar', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Produção Mensal',
                'verbose_name_plural': 'Produções Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('sistema', 'mes', 'ano')},
            },
        ),
    ]
