# Generated by Django 5.2.9 on 2025-12-10 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('tamanho_sistema', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_instalacao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_sistema', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial'), ('RURAL', 'Rural')], default='RESIDENCIAL', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(default='Solar Energy Solutions', max_length=200)),
                ('email_contato', models.EmailField(default='contato@solarenergy.com', max_length=254)),
                ('telefone_contato', models.CharField(default='(11) 99999-9999', max_length=20)),
                ('endereco_empresa', models.TextField(default='Av. Paulista, 1000 - São Paulo/SP')),
                ('cnpj', models.CharField(default='12.345.678/0001-99', max_length=18)),
                ('taxa_juros', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('prazo_maximo', models.IntegerField(default=60)),
                ('notificacoes_email', models.BooleanField(default=True)),
                ('notificacoes_sms', models.BooleanField(default=False)),
                ('relatorio_automatico', models.BooleanField(default=True)),
                ('tema_escuro', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.AlterModelOptions(
            name='producaomensal',
            options={'ordering': ['-ano', '-mes']},
        ),
        migrations.RemoveField(
            model_name='sistemasolar',
            name='atualizado_em',
        ),
        migrations.AlterField(
            model_name='producaomensal',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producaomensal',
            name='irradiacao_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producaomensal',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producaomensal',
            name='producao_kwh',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producaomensal',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='api.sistemasolar'),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='garantia_inversor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='garantia_paineis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='inclinacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='marca_inversor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='marca_painel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='modelo_inversor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='modelo_painel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='orientacao',
            field=models.CharField(choices=[('NORTE', 'Norte'), ('NORDESTE', 'Nordeste'), ('LESTE', 'Leste'), ('SUDESTE', 'Sudeste'), ('SUL', 'Sul'), ('SUDOESTE', 'Sudoeste'), ('OESTE', 'Oeste'), ('NOROESTE', 'Noroeste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='potencia_inversor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='potencia_painel',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='quantidade_paineis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sistemasolar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='api.cliente'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('dados', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='ClienteSolar',
        ),
    ]
